const PDFDocument = require("pdfkit");
const fs = require("fs");
const path = require("path");

/**
 * Generate a PDF report for a completed interview.
 * Returns the absolute path to the generated PDF.
 */
const generateReportPdf = async (report, user, interview) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ margin: 50 });
      const filename = `Report_${report.interviewId}.pdf`;
      const reportsDir = path.join(process.cwd(), "uploads", "reports");
      
      // Ensure the directory exists
      if (!fs.existsSync(reportsDir)) {
        fs.mkdirSync(reportsDir, { recursive: true });
      }

      const filePath = path.join(reportsDir, filename);
      const stream = fs.createWriteStream(filePath);

      doc.pipe(stream);

      // Title
      doc.fontSize(24).fillColor("#0A0F1E").text("Interview Performance Report", { align: "center" });
      doc.moveDown(0.5);

      // Candidate Info
      doc.fontSize(14).fillColor("#334155").text(`Candidate: ${user.name}`);
      doc.fontSize(12).text(`Email: ${user.email}`);
      doc.text(`Role Assessed: ${interview.role}`);
      doc.text(`Date completed: ${new Date(report.createdAt).toLocaleString("en-IN")}`);
      doc.moveDown(1);

      // Scores
      doc.fontSize(18).fillColor("#06B6D4").text(`Overall Score: ${report.overallScore}/10`);
      doc.moveDown(0.5);
      
      doc.fontSize(12).fillColor("#334155").text(`Technical Score: ${report.technicalScore || "N/A"}/10`);
      doc.text(`Communication Score: ${report.communicationScore || "N/A"}/10`);
      doc.text(`Problem Solving Score: ${report.problemSolvingScore || "N/A"}/10`);
      
      if (report.codeQualityScore) {
        doc.text(`Code Quality Score: ${report.codeQualityScore}/10`);
      }
      doc.moveDown(1);

      // Overall Feedback
      doc.fontSize(14).fillColor("#0A0F1E").text("Overall Feedback");
      doc.fontSize(11).fillColor("#475569").text(report.overallFeedback || "No feedback available at this time.");
      doc.moveDown(1);

      // Strengths
      doc.fontSize(14).fillColor("#0A0F1E").text("Key Strengths");
      (report.strengths || []).forEach(s => {
        doc.fontSize(11).fillColor("#475569").text(`• ${s}`);
      });
      doc.moveDown(1);

      // Weaknesses
      doc.fontSize(14).fillColor("#0A0F1E").text("Areas for Improvement");
      (report.weaknesses || []).forEach(w => {
        doc.fontSize(11).fillColor("#475569").text(`• ${w}`);
      });
      doc.moveDown(1);

      // Recommendation
      if (report.recommendation) {
        doc.fontSize(14).fillColor("#0A0F1E").text("AI Recommendation");
        doc.fontSize(12).fillColor("#6366F1").text(report.recommendation.replace(/_/g, " ").toUpperCase());
      }
      
      // Footer
      doc.moveDown(2);
      doc.fontSize(10).fillColor("#cbd5e1").text("Automated report generated by Interview AI Platform", { align: "center" });

      doc.end();

      stream.on("finish", () => {
        resolve(filePath);
      });

      stream.on("error", (err) => {
        reject(err);
      });
    } catch (err) {
      reject(err);
    }
  });
};

module.exports = { generateReportPdf };
