import { useState } from 'react'
import { useNavigate, Link } from 'react-router-dom'
import { motion } from 'framer-motion'
import { useOrgAuth } from '../../context/OrgAuthContext'
import { createTemplate } from '../../api/orgAPI'
import {
  ArrowLeft, Mic, Wand2, Clock, Hash, Shield, Calendar,
  ChevronRight, Loader2, Copy, CheckCircle2, AlertTriangle
} from 'lucide-react'
import toast from 'react-hot-toast'

const TYPES = ['technical', 'hr', 'behavioral', 'system_design', 'mixed']
const DIFFICULTIES = ['easy', 'medium', 'hard', 'adaptive']

function FieldLabel({ children, required }) {
  return (
    <label className="block text-xs font-mono text-slate-400 mb-1.5">
      {children}{required && <span className="text-rose ml-0.5">*</span>}
    </label>
  )
}

export default function OrgCreateInterviewPage() {
  const navigate = useNavigate()
  const { org } = useOrgAuth()
  const [loading, setLoading] = useState(false)
  const [created, setCreated] = useState(null)
  const [copied, setCopied] = useState(false)
  const [techInput, setTechInput] = useState('')

  const [form, setForm] = useState({
    title: '',
    role: '',
    interviewType: 'technical',
    difficulty: 'adaptive',
    duration: 45,
    questionCount: 8,
    techStack: [],
    instructions: '',
    deadline: '',
    maxAttempts: 1,
    proctoringEnabled: true,
  })

  const set = (k, v) => setForm((p) => ({ ...p, [k]: v }))

  const addTech = (e) => {
    if (e.key === 'Enter' || e.key === ',') {
      e.preventDefault()
      const tag = techInput.trim()
      if (tag && !form.techStack.includes(tag)) {
        set('techStack', [...form.techStack, tag])
      }
      setTechInput('')
    }
  }

  const removeTech = (t) => set('techStack', form.techStack.filter((x) => x !== t))

  const handleSubmit = async (e) => {
    e.preventDefault()
    if (!form.title || !form.role) {
      toast.error('Title and role are required')
      return
    }
    setLoading(true)
    try {
      const res = await createTemplate(form)
      setCreated(res.data.data)
      toast.success('Interview created! Questions generated by AI.')
    } catch (err) {
      toast.error(err.response?.data?.message || 'Failed to create interview')
    } finally {
      setLoading(false)
    }
  }

  const copyLink = () => {
    if (!created) return
    navigator.clipboard.writeText(created.joinUrl)
    setCopied(true)
    toast.success('Join link copied!')
    setTimeout(() => setCopied(false), 2000)
  }

  // Success state
  if (created) {
    return (
      <div className="min-h-screen bg-void flex flex-col items-center justify-center p-4">
        <motion.div initial={{ opacity: 0, scale: 0.9 }} animate={{ opacity: 1, scale: 1 }}
          className="w-full max-w-lg bg-card border border-border rounded-2xl p-8 text-center">
          <div className="w-16 h-16 bg-emerald/10 border border-emerald/30 rounded-full flex items-center justify-center mx-auto mb-4">
            <CheckCircle2 className="w-8 h-8 text-emerald" />
          </div>
          <h2 className="font-display font-bold text-2xl text-zinc-900 dark:text-white mb-2">Interview Created!</h2>
          <p className="text-slate-400 font-body text-sm mb-6">
            AI has generated {created.questions?.length} questions. Share the link with candidates.
          </p>

          {/* Share link */}
          <div className="bg-surface border border-border rounded-xl p-4 mb-4">
            <p className="text-[10px] font-mono text-slate-500 mb-2 text-left">JOIN LINK</p>
            <div className="flex items-center gap-2">
              <code className="flex-1 text-xs text-cyan font-mono break-all text-left">{created.joinUrl}</code>
              <button onClick={copyLink}
                className={`flex-shrink-0 p-2 rounded-lg border transition-all ${copied ? 'border-emerald/30 bg-emerald/10 text-emerald' : 'border-border text-slate-500 hover:border-cyan/30 hover:text-cyan'}`}>
                {copied ? <CheckCircle2 className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
              </button>
            </div>
          </div>

          {/* Questions preview */}
          <div className="bg-surface border border-border rounded-xl p-4 mb-6 text-left">
            <p className="text-[10px] font-mono text-slate-500 mb-3">GENERATED QUESTIONS ({created.questions?.length})</p>
            <div className="space-y-2 max-h-40 overflow-y-auto">
              {created.questions?.map((q, i) => (
                <div key={q.questionId} className="flex items-start gap-2">
                  <span className="text-[10px] font-mono text-slate-600 mt-0.5 flex-shrink-0">Q{i + 1}</span>
                  <div>
                    <span className={`text-[9px] font-mono px-1.5 py-0.5 rounded mr-1 ${
                      q.questionType === 'code' ? 'bg-violet/10 text-violet' :
                      q.questionType === 'system_design' ? 'bg-cyan/10 text-cyan' :
                      'bg-slate-800 text-slate-400'
                    }`}>{q.questionType}</span>
                    <span className="text-xs text-slate-300 font-body">{q.question.slice(0, 80)}...</span>
                  </div>
                </div>
              ))}
            </div>
          </div>

          <div className="flex gap-3">
            <button onClick={() => navigate('/org/dashboard')}
              className="flex-1 py-2.5 border border-border rounded-xl text-sm text-slate-400 hover:border-slate-600 transition-all font-body">
              ← Dashboard
            </button>
            <button onClick={() => navigate(`/org/interview/${created.templateId || created.joinUrl?.split('/').slice(-2)[0]?.replace('?', '')}/leaderboard`)}
              className="flex-1 py-2.5 bg-gradient-to-r from-violet to-cyan text-void font-display font-bold text-sm rounded-xl hover:shadow-lg transition-all">
              View Leaderboard
            </button>
          </div>
        </motion.div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-void">
      {/* Nav */}
      <nav className="border-b border-border bg-surface/50 backdrop-blur-sm sticky top-0 z-40">
        <div className="max-w-4xl mx-auto px-4 h-14 flex items-center gap-3">
          <button onClick={() => navigate('/org/dashboard')} className="text-slate-500 hover:text-zinc-900 dark:text-white transition-colors">
            <ArrowLeft className="w-4 h-4" />
          </button>
          <div className="w-0.5 h-4 bg-border" />
          <div className="flex items-center gap-2">
            <Wand2 className="w-4 h-4 text-violet" />
            <span className="font-display font-semibold text-zinc-900 dark:text-white text-sm">Create Interview</span>
          </div>
          <div className="ml-auto flex items-center gap-2 text-[10px] font-mono text-slate-500">
            <AlertTriangle className="w-3 h-3 text-amber" />
            AI generates questions after submission
          </div>
        </div>
      </nav>

      <form onSubmit={handleSubmit} className="max-w-4xl mx-auto px-4 py-8">
        <div className="grid lg:grid-cols-3 gap-6">

          {/* Left — main fields */}
          <div className="lg:col-span-2 space-y-5">
            <div className="bg-card border border-border rounded-2xl p-6">
              <h2 className="font-display font-semibold text-zinc-900 dark:text-white mb-5 flex items-center gap-2">
                <span className="w-5 h-5 bg-violet/20 text-violet rounded-md flex items-center justify-center text-[10px] font-bold">1</span>
                Basic Info
              </h2>
              <div className="space-y-4">
                <div>
                  <FieldLabel required>Interview Title</FieldLabel>
                  <input value={form.title} onChange={(e) => set('title', e.target.value)}
                    placeholder="e.g., SDE Hiring Round 1 — Batch 2025"
                    className="w-full bg-surface border border-border rounded-xl px-4 py-3 text-sm text-slate-200 outline-none focus:border-violet/40 placeholder-slate-600 font-body"
                    required />
                </div>
                <div>
                  <FieldLabel required>Target Role</FieldLabel>
                  <input value={form.role} onChange={(e) => set('role', e.target.value)}
                    placeholder="e.g., Software Development Engineer"
                    className="w-full bg-surface border border-border rounded-xl px-4 py-3 text-sm text-slate-200 outline-none focus:border-violet/40 placeholder-slate-600 font-body"
                    required />
                </div>
                <div>
                  <FieldLabel>Instructions for Candidates</FieldLabel>
                  <textarea value={form.instructions} onChange={(e) => set('instructions', e.target.value)}
                    placeholder="e.g., This is a 45-minute AI interview. Keep your camera on and speak clearly..."
                    rows={3}
                    className="w-full bg-surface border border-border rounded-xl px-4 py-3 text-sm text-slate-200 outline-none focus:border-violet/40 placeholder-slate-600 font-body resize-none" />
                </div>
              </div>
            </div>

            <div className="bg-card border border-border rounded-2xl p-6">
              <h2 className="font-display font-semibold text-zinc-900 dark:text-white mb-5 flex items-center gap-2">
                <span className="w-5 h-5 bg-violet/20 text-violet rounded-md flex items-center justify-center text-[10px] font-bold">2</span>
                Interview Format
              </h2>
              <div className="space-y-4">
                {/* Type */}
                <div>
                  <FieldLabel>Interview Type</FieldLabel>
                  <div className="flex flex-wrap gap-2">
                    {TYPES.map((t) => (
                      <button key={t} type="button" onClick={() => set('interviewType', t)}
                        className={`px-3 py-1.5 rounded-lg text-xs font-body font-medium capitalize transition-all border ${
                          form.interviewType === t
                            ? 'border-violet/50 bg-violet/10 text-violet'
                            : 'border-border text-slate-500 hover:border-violet/30'
                        }`}>{t.replace('_', ' ')}</button>
                    ))}
                  </div>
                </div>

                {/* Difficulty */}
                <div>
                  <FieldLabel>Difficulty</FieldLabel>
                  <div className="flex flex-wrap gap-2">
                    {DIFFICULTIES.map((d) => (
                      <button key={d} type="button" onClick={() => set('difficulty', d)}
                        className={`px-3 py-1.5 rounded-lg text-xs font-body font-medium capitalize transition-all border ${
                          form.difficulty === d
                            ? 'border-cyan/50 bg-cyan/10 text-cyan'
                            : 'border-border text-slate-500 hover:border-cyan/30'
                        }`}>{d}</button>
                    ))}
                  </div>
                </div>

                {/* Tech Stack */}
                <div>
                  <FieldLabel>Tech Stack Required</FieldLabel>
                  <div className="bg-surface border border-border rounded-xl p-3">
                    <div className="flex flex-wrap gap-1.5 mb-2">
                      {form.techStack.map((t) => (
                        <span key={t} className="flex items-center gap-1 text-[11px] font-mono bg-violet/10 text-violet border border-violet/20 px-2 py-0.5 rounded-full">
                          {t}
                          <button type="button" onClick={() => removeTech(t)} className="text-violet/60 hover:text-rose ml-0.5">×</button>
                        </span>
                      ))}
                    </div>
                    <input value={techInput} onChange={(e) => setTechInput(e.target.value)} onKeyDown={addTech}
                      placeholder="Type a tech and press Enter (e.g. React, Node.js)"
                      className="w-full bg-transparent text-sm text-slate-300 outline-none placeholder-slate-600 font-body" />
                  </div>
                  <p className="text-[10px] text-slate-600 mt-1">Press Enter or comma to add each technology</p>
                </div>
              </div>
            </div>
          </div>

          {/* Right — config panel */}
          <div className="space-y-4">
            <div className="bg-card border border-border rounded-2xl p-5 space-y-4 sticky top-20">
              <h2 className="font-display font-semibold text-zinc-900 dark:text-white flex items-center gap-2">
                <span className="w-5 h-5 bg-cyan/20 text-cyan rounded-md flex items-center justify-center text-[10px] font-bold">3</span>
                Configuration
              </h2>

              <div>
                <FieldLabel>Duration (minutes)</FieldLabel>
                <div className="flex items-center gap-2">
                  <Clock className="w-4 h-4 text-slate-600 flex-shrink-0" />
                  <input type="number" value={form.duration} onChange={(e) => set('duration', parseInt(e.target.value))}
                    min={10} max={180}
                    className="flex-1 bg-surface border border-border rounded-lg px-3 py-2 text-sm text-slate-200 outline-none focus:border-cyan/40 font-mono" />
                  <span className="text-xs text-slate-500">min</span>
                </div>
              </div>

              <div>
                <FieldLabel>Number of Questions</FieldLabel>
                <div className="flex items-center gap-2">
                  <Hash className="w-4 h-4 text-slate-600 flex-shrink-0" />
                  <input type="number" value={form.questionCount} onChange={(e) => set('questionCount', parseInt(e.target.value))}
                    min={3} max={20}
                    className="flex-1 bg-surface border border-border rounded-lg px-3 py-2 text-sm text-slate-200 outline-none focus:border-cyan/40 font-mono" />
                  <span className="text-xs text-slate-500 w-8">3–20</span>
                </div>
              </div>

              <div>
                <FieldLabel>Max Attempts per Candidate</FieldLabel>
                <input type="number" value={form.maxAttempts} onChange={(e) => set('maxAttempts', parseInt(e.target.value))}
                  min={1} max={5}
                  className="w-full bg-surface border border-border rounded-lg px-3 py-2 text-sm text-slate-200 outline-none focus:border-cyan/40 font-mono" />
              </div>

              <div>
                <FieldLabel>Deadline (optional)</FieldLabel>
                <div className="flex items-center gap-2">
                  <Calendar className="w-4 h-4 text-slate-600 flex-shrink-0" />
                  <input type="datetime-local" value={form.deadline} onChange={(e) => set('deadline', e.target.value)}
                    className="flex-1 bg-surface border border-border rounded-lg px-3 py-2 text-xs text-slate-200 outline-none focus:border-cyan/40 font-mono" />
                </div>
              </div>

              {/* Proctoring toggle */}
              <div className="flex items-center justify-between py-2 border-t border-border">
                <div className="flex items-center gap-2">
                  <Shield className="w-4 h-4 text-slate-500" />
                  <span className="text-xs font-body text-slate-400">Proctoring</span>
                </div>
                <button type="button" onClick={() => set('proctoringEnabled', !form.proctoringEnabled)}
                  className={`relative w-10 h-5 rounded-full transition-all ${form.proctoringEnabled ? 'bg-emerald' : 'bg-slate-700'}`}>
                  <span className={`absolute top-0.5 w-4 h-4 rounded-full bg-white shadow transition-all ${form.proctoringEnabled ? 'left-5' : 'left-0.5'}`} />
                </button>
              </div>

              <button type="submit" disabled={loading}
                className="w-full py-3 bg-gradient-to-r from-violet to-cyan text-void font-display font-bold rounded-xl hover:shadow-lg hover:scale-[1.01] active:scale-[0.99] transition-all disabled:opacity-50 flex items-center justify-center gap-2">
                {loading ? (
                  <><Loader2 className="w-4 h-4 animate-spin" />Generating questions...</>
                ) : (
                  <><Wand2 className="w-4 h-4" />Generate & Create</>
                )}
              </button>

              {loading && (
                <p className="text-[10px] text-slate-500 text-center font-mono">
                  AI is generating {form.questionCount} questions for {form.role}...
                </p>
              )}
            </div>
          </div>
        </div>
      </form>
    </div>
  )
}
