import { useState } from 'react'
import { useNavigate, Link } from 'react-router-dom'
import { motion } from 'framer-motion'
import { useOrgAuth } from '../../context/OrgAuthContext'
import { createTemplate } from '../../api/orgAPI'
import {
  ArrowLeft, Mic, Wand2, Clock, Hash, Shield, Calendar,
  ChevronRight, Loader2, Copy, CheckCircle2, AlertTriangle
} from 'lucide-react'
import toast from 'react-hot-toast'
import { Button, Badge } from '../../components/ui/index'

const TYPES = ['technical', 'hr', 'behavioral', 'system_design', 'mixed']
const DIFFICULTIES = ['easy', 'medium', 'hard', 'adaptive']

function FieldLabel({ children, required }) {
  return (
    <label className="block text-xs font-medium text-zinc-600 dark:text-zinc-400 mb-1.5" style={{ fontFamily: 'Inter, system-ui' }}>
      {children}{required && <span className="text-red-500 ml-0.5">*</span>}
    </label>
  )
}

export default function OrgCreateInterviewPage() {
  const navigate = useNavigate()
  const { org } = useOrgAuth()
  const [loading, setLoading] = useState(false)
  const [created, setCreated] = useState(null)
  const [copied, setCopied] = useState(false)
  const [techInput, setTechInput] = useState('')

  const [form, setForm] = useState({
    title: '',
    role: '',
    interviewType: 'technical',
    difficulty: 'adaptive',
    duration: 45,
    questionCount: 8,
    techStack: [],
    instructions: '',
    deadline: '',
    maxAttempts: 1,
    proctoringEnabled: true,
  })

  const set = (k, v) => setForm((p) => ({ ...p, [k]: v }))

  const addTech = (e) => {
    if (e.key === 'Enter' || e.key === ',') {
      e.preventDefault()
      const tag = techInput.trim()
      if (tag && !form.techStack.includes(tag)) {
        set('techStack', [...form.techStack, tag])
      }
      setTechInput('')
    }
  }

  const removeTech = (t) => set('techStack', form.techStack.filter((x) => x !== t))

  const handleSubmit = async (e) => {
    e.preventDefault()
    if (!form.title || !form.role) {
      toast.error('Title and role are required')
      return
    }
    setLoading(true)
    try {
      const res = await createTemplate(form)
      setCreated(res.data.data)
      toast.success('Interview created! Questions generated by AI.')
    } catch (err) {
      toast.error(err.response?.data?.message || 'Failed to create interview')
    } finally {
      setLoading(false)
    }
  }

  const copyLink = () => {
    if (!created) return
    navigator.clipboard.writeText(created.joinUrl)
    setCopied(true)
    toast.success('Join link copied!')
    setTimeout(() => setCopied(false), 2000)
  }

  // Success state
  if (created) {
    return (
      <div className="min-h-screen bg-zinc-50 dark:bg-zinc-950 flex flex-col items-center justify-center p-4">
        <motion.div initial={{ opacity: 0, scale: 0.9 }} animate={{ opacity: 1, scale: 1 }}
          className="w-full max-w-lg bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 rounded-2xl p-8 text-center shadow-sm">
          <div className="w-16 h-16 bg-green-50 dark:bg-green-900/30 border border-green-200 dark:border-green-800/50 rounded-full flex items-center justify-center mx-auto mb-4">
            <CheckCircle2 className="w-8 h-8 text-green-600 dark:text-green-500" />
          </div>
          <h2 className="text-2xl font-bold text-zinc-900 dark:text-zinc-50 mb-2" style={{ fontFamily: 'Poppins, sans-serif' }}>Interview Created!</h2>
          <p className="text-zinc-500 text-sm mb-6">
            AI has generated {created.questions?.length} questions. Share the link with candidates.
          </p>

          {/* Share link */}
          <div className="bg-zinc-50 dark:bg-zinc-950/50 border border-zinc-200 dark:border-zinc-800 rounded-xl p-4 mb-4 text-left">
            <p className="text-[10px] font-semibold text-zinc-500 mb-2 tracking-wider">JOIN LINK</p>
            <div className="flex items-center gap-2">
              <code className="flex-1 text-xs text-blue-600 dark:text-blue-400 font-mono break-all">{created.joinUrl}</code>
              <button onClick={copyLink}
                className={`flex-shrink-0 p-2 rounded-lg border transition-all ${copied ? 'border-green-200 bg-green-50 text-green-600 dark:border-green-800 dark:bg-green-900/30 dark:text-green-400' : 'border-zinc-200 dark:border-zinc-800 text-zinc-500 hover:border-blue-300 hover:text-blue-500'}`}>
                {copied ? <CheckCircle2 className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
              </button>
            </div>
          </div>

          {/* Questions preview */}
          <div className="bg-zinc-50 dark:bg-zinc-950/50 border border-zinc-200 dark:border-zinc-800 rounded-xl p-4 mb-6 text-left">
            <p className="text-[10px] font-semibold text-zinc-500 mb-3 tracking-wider">GENERATED QUESTIONS ({created.questions?.length})</p>
            <div className="space-y-2 max-h-40 overflow-y-auto pr-2 custom-scrollbar">
              {created.questions?.map((q, i) => (
                <div key={q.questionId} className="flex items-start gap-2">
                  <span className="text-[10px] font-mono text-zinc-500 mt-0.5 flex-shrink-0">Q{i + 1}</span>
                  <div>
                    <span className={`text-[9px] font-semibold px-1.5 py-0.5 rounded mr-1.5 uppercase tracking-wider ${
                      q.questionType === 'code' ? 'bg-blue-50 dark:bg-blue-900/30 text-blue-600 dark:text-blue-400' :
                      q.questionType === 'system_design' ? 'bg-indigo-50 dark:bg-indigo-900/30 text-indigo-600 dark:text-indigo-400' :
                      'bg-zinc-100 dark:bg-zinc-800 text-zinc-600 dark:text-zinc-400'
                    }`}>{q.questionType}</span>
                    <span className="text-xs text-zinc-700 dark:text-zinc-300">{q.question.slice(0, 80)}...</span>
                  </div>
                </div>
              ))}
            </div>
          </div>

          <div className="flex gap-3">
            <Button variant="outline" onClick={() => navigate('/org/dashboard')} className="flex-1">
              ← Dashboard
            </Button>
            <Button variant="primary" onClick={() => navigate(`/org/interview/${created.templateId || created.joinUrl?.split('/').slice(-2)[0]?.replace('?', '')}/leaderboard`)} className="flex-1">
              View Leaderboard
            </Button>
          </div>
        </motion.div>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-zinc-50 dark:bg-zinc-950" style={{ fontFamily: 'Inter, system-ui' }}>
      {/* Nav */}
      <nav className="border-b border-zinc-200 dark:border-zinc-800 bg-white/50 dark:bg-zinc-900/50 backdrop-blur-sm sticky top-0 z-40">
        <div className="max-w-4xl mx-auto px-4 h-14 flex items-center gap-3">
          <button onClick={() => navigate('/org/dashboard')} className="text-zinc-500 hover:text-zinc-900 dark:text-zinc-400 dark:hover:text-white transition-colors">
            <ArrowLeft className="w-4 h-4" />
          </button>
          <div className="w-0.5 h-4 bg-zinc-200 dark:bg-zinc-800" />
          <div className="flex items-center gap-2">
            <Wand2 className="w-4 h-4 text-blue-600 dark:text-blue-500" />
            <span className="font-semibold text-zinc-900 dark:text-zinc-100 text-sm" style={{ fontFamily: 'Poppins, sans-serif' }}>Create Interview</span>
          </div>
          <div className="ml-auto flex items-center gap-1.5 text-[10px] font-medium text-amber-600 dark:text-amber-500 bg-amber-50 dark:bg-amber-900/20 px-2.5 py-1 rounded-full border border-amber-200 dark:border-amber-800/50">
            <AlertTriangle className="w-3 h-3" />
            AI generates questions automatically
          </div>
        </div>
      </nav>

      <form onSubmit={handleSubmit} className="max-w-4xl mx-auto px-4 py-8">
        <div className="grid lg:grid-cols-3 gap-6">

          {/* Left — main fields */}
          <div className="lg:col-span-2 space-y-5">
            <div className="bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 rounded-2xl p-6 shadow-sm">
              <h2 className="font-bold text-zinc-900 dark:text-zinc-50 mb-5 flex items-center gap-2" style={{ fontFamily: 'Poppins, sans-serif' }}>
                <span className="w-5 h-5 bg-blue-50 dark:bg-blue-900/30 text-blue-600 dark:text-blue-400 rounded-md flex items-center justify-center text-[10px] font-bold">1</span>
                Basic Info
              </h2>
              <div className="space-y-4">
                <div>
                  <FieldLabel required>Interview Title</FieldLabel>
                  <input value={form.title} onChange={(e) => set('title', e.target.value)}
                    placeholder="e.g., SDE Hiring Round 1 — Batch 2025"
                    className="w-full bg-white dark:bg-zinc-950 border border-zinc-200 dark:border-zinc-800 rounded-xl px-4 py-3 text-sm text-zinc-900 dark:text-zinc-100 outline-none focus:border-blue-500 focus:ring-1 focus:ring-blue-500/20 placeholder-zinc-400 dark:placeholder-zinc-600 transition-all"
                    required />
                </div>
                <div>
                  <FieldLabel required>Target Role</FieldLabel>
                  <input value={form.role} onChange={(e) => set('role', e.target.value)}
                    placeholder="e.g., Software Development Engineer"
                    className="w-full bg-white dark:bg-zinc-950 border border-zinc-200 dark:border-zinc-800 rounded-xl px-4 py-3 text-sm text-zinc-900 dark:text-zinc-100 outline-none focus:border-blue-500 focus:ring-1 focus:ring-blue-500/20 placeholder-zinc-400 dark:placeholder-zinc-600 transition-all"
                    required />
                </div>
                <div>
                  <FieldLabel>Instructions for Candidates</FieldLabel>
                  <textarea value={form.instructions} onChange={(e) => set('instructions', e.target.value)}
                    placeholder="e.g., This is a 45-minute AI interview. Keep your camera on and speak clearly..."
                    rows={3}
                    className="w-full bg-white dark:bg-zinc-950 border border-zinc-200 dark:border-zinc-800 rounded-xl px-4 py-3 text-sm text-zinc-900 dark:text-zinc-100 outline-none focus:border-blue-500 focus:ring-1 focus:ring-blue-500/20 placeholder-zinc-400 dark:placeholder-zinc-600 transition-all resize-none" />
                </div>
              </div>
            </div>

            <div className="bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 rounded-2xl p-6 shadow-sm">
              <h2 className="font-bold text-zinc-900 dark:text-zinc-50 mb-5 flex items-center gap-2" style={{ fontFamily: 'Poppins, sans-serif' }}>
                <span className="w-5 h-5 bg-blue-50 dark:bg-blue-900/30 text-blue-600 dark:text-blue-400 rounded-md flex items-center justify-center text-[10px] font-bold">2</span>
                Interview Format
              </h2>
              <div className="space-y-5">
                {/* Type */}
                <div>
                  <FieldLabel>Interview Type</FieldLabel>
                  <div className="flex flex-wrap gap-2">
                    {TYPES.map((t) => (
                      <button key={t} type="button" onClick={() => set('interviewType', t)}
                        className={`px-4 py-2 rounded-lg text-xs font-semibold capitalize transition-all border ${
                          form.interviewType === t
                            ? 'border-blue-500 bg-blue-50 text-blue-700 dark:bg-blue-900/20 dark:text-blue-400'
                            : 'border-zinc-200 dark:border-zinc-800 text-zinc-600 dark:text-zinc-400 hover:border-blue-300 dark:hover:border-blue-700 hover:bg-zinc-50 dark:hover:bg-zinc-800/50'
                        }`}>{t.replace('_', ' ')}</button>
                    ))}
                  </div>
                </div>

                {/* Difficulty */}
                <div>
                  <FieldLabel>Difficulty</FieldLabel>
                  <div className="flex flex-wrap gap-2">
                    {DIFFICULTIES.map((d) => (
                      <button key={d} type="button" onClick={() => set('difficulty', d)}
                        className={`px-4 py-2 rounded-lg text-xs font-semibold capitalize transition-all border ${
                          form.difficulty === d
                            ? 'border-blue-500 bg-blue-50 text-blue-700 dark:bg-blue-900/20 dark:text-blue-400'
                            : 'border-zinc-200 dark:border-zinc-800 text-zinc-600 dark:text-zinc-400 hover:border-blue-300 dark:hover:border-blue-700 hover:bg-zinc-50 dark:hover:bg-zinc-800/50'
                        }`}>{d}</button>
                    ))}
                  </div>
                </div>

                {/* Tech Stack */}
                <div>
                  <FieldLabel>Tech Stack Required</FieldLabel>
                  <div className="bg-white dark:bg-zinc-950 border border-zinc-200 dark:border-zinc-800 rounded-xl p-3 focus-within:border-blue-500 focus-within:ring-1 focus-within:ring-blue-500/20 transition-all">
                    <div className="flex flex-wrap gap-2 mb-2">
                      {form.techStack.map((t) => (
                        <span key={t} className="flex items-center gap-1.5 text-xs font-medium bg-blue-50 dark:bg-blue-900/30 text-blue-700 dark:text-blue-400 border border-blue-200 dark:border-blue-800/50 px-2.5 py-1 rounded-md">
                          {t}
                          <button type="button" onClick={() => removeTech(t)} className="text-blue-400 hover:text-red-500 transition-colors focus:outline-none">×</button>
                        </span>
                      ))}
                    </div>
                    <input value={techInput} onChange={(e) => setTechInput(e.target.value)} onKeyDown={addTech}
                      placeholder={form.techStack.length === 0 ? "Type a tech and press Enter (e.g. React, Node.js)" : "Add more tech..."}
                      className="w-full bg-transparent text-sm text-zinc-900 dark:text-zinc-100 outline-none placeholder-zinc-400 dark:placeholder-zinc-600" />
                  </div>
                  <p className="text-[10px] text-zinc-500 mt-1.5">Press Enter or comma to add each technology</p>
                </div>
              </div>
            </div>
          </div>

          {/* Right — config panel */}
          <div className="space-y-4">
            <div className="bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 rounded-2xl p-5 space-y-5 sticky top-20 shadow-sm">
              <h2 className="font-bold text-zinc-900 dark:text-zinc-50 flex items-center gap-2" style={{ fontFamily: 'Poppins, sans-serif' }}>
                <span className="w-5 h-5 bg-blue-50 dark:bg-blue-900/30 text-blue-600 dark:text-blue-400 rounded-md flex items-center justify-center text-[10px] font-bold">3</span>
                Configuration
              </h2>

              <div>
                <FieldLabel>Duration (minutes)</FieldLabel>
                <div className="flex items-center gap-2">
                  <Clock className="w-4 h-4 text-zinc-400 flex-shrink-0" />
                  <input type="number" value={form.duration} onChange={(e) => set('duration', parseInt(e.target.value))}
                    min={10} max={180}
                    className="flex-1 bg-white dark:bg-zinc-950 border border-zinc-200 dark:border-zinc-800 rounded-lg px-3 py-2 text-sm text-zinc-900 dark:text-zinc-100 outline-none focus:border-blue-500 focus:ring-1 focus:ring-blue-500/20 font-mono transition-all" />
                  <span className="text-xs text-zinc-500">min</span>
                </div>
              </div>

              <div>
                <FieldLabel>Number of Questions</FieldLabel>
                <div className="flex items-center gap-2">
                  <Hash className="w-4 h-4 text-zinc-400 flex-shrink-0" />
                  <input type="number" value={form.questionCount} onChange={(e) => set('questionCount', parseInt(e.target.value))}
                    min={3} max={20}
                    className="flex-1 bg-white dark:bg-zinc-950 border border-zinc-200 dark:border-zinc-800 rounded-lg px-3 py-2 text-sm text-zinc-900 dark:text-zinc-100 outline-none focus:border-blue-500 focus:ring-1 focus:ring-blue-500/20 font-mono transition-all" />
                  <span className="text-xs text-zinc-500 w-8">3–20</span>
                </div>
              </div>

              <div>
                <FieldLabel>Max Attempts per Candidate</FieldLabel>
                <input type="number" value={form.maxAttempts} onChange={(e) => set('maxAttempts', parseInt(e.target.value))}
                  min={1} max={5}
                  className="w-full bg-white dark:bg-zinc-950 border border-zinc-200 dark:border-zinc-800 rounded-lg px-3 py-2 text-sm text-zinc-900 dark:text-zinc-100 outline-none focus:border-blue-500 focus:ring-1 focus:ring-blue-500/20 font-mono transition-all" />
              </div>

              <div>
                <FieldLabel>Deadline (optional)</FieldLabel>
                <div className="flex items-center gap-2">
                  <Calendar className="w-4 h-4 text-zinc-400 flex-shrink-0" />
                  <input type="datetime-local" value={form.deadline} onChange={(e) => set('deadline', e.target.value)}
                    className="flex-1 bg-white dark:bg-zinc-950 border border-zinc-200 dark:border-zinc-800 rounded-lg px-3 py-2 text-xs text-zinc-900 dark:text-zinc-100 outline-none focus:border-blue-500 focus:ring-1 focus:ring-blue-500/20 font-mono transition-all" />
                </div>
              </div>

              {/* Proctoring toggle */}
              <div className="flex items-center justify-between py-3 border-t border-zinc-100 dark:border-zinc-800">
                <div className="flex items-center gap-2">
                  <Shield className="w-4 h-4 text-zinc-500" />
                  <span className="text-xs font-medium text-zinc-600 dark:text-zinc-400">Proctoring</span>
                </div>
                <button type="button" onClick={() => set('proctoringEnabled', !form.proctoringEnabled)}
                  className={`relative w-10 h-5 rounded-full transition-colors duration-200 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2 dark:focus:ring-offset-zinc-900 ${form.proctoringEnabled ? 'bg-blue-600' : 'bg-zinc-300 dark:bg-zinc-700'}`}>
                  <span className={`absolute top-0.5 w-4 h-4 rounded-full bg-white shadow-sm transition-transform duration-200 ${form.proctoringEnabled ? 'translate-x-5' : 'translate-x-0.5'}`} />
                </button>
              </div>

              <Button
                type="submit"
                variant="primary"
                size="lg"
                loading={loading}
                className="w-full"
              >
                {!loading && <Wand2 className="w-4 h-4" />}
                Generate & Create
              </Button>

              {loading && (
                <p className="text-[10px] text-zinc-500 text-center font-mono mt-3 bg-zinc-50 dark:bg-zinc-950 p-2 rounded border border-zinc-200 dark:border-zinc-800">
                  AI is generating {form.questionCount} questions for {form.role}...
                </p>
              )}
            </div>
          </div>
        </div>
      </form>
    </div>
  )
}
